name: dev_compiler
version: 0.2.0
description: >
  Experimental Dart to JavaScript compiler designed to create idiomatic,
  readable JavaScript output.

author: Dart Dev Compiler team <dev-compiler@dartlang.org>
homepage: https://github.com/dart-lang/dev_compiler

dependencies:
  analyzer: ^0.27.4-alpha.2
  angular2: 2.0.0-beta.15
  args: ^0.13.0
  barback: ^0.15.2
  bazel_worker: ^0.1.0
  build: ^0.3.0
  cli_util: ^0.0.1
  func: ^0.1.0
  html: ^0.12.0
  js: ^0.6.0
  path: ^1.3.0
  pub_semver: ^1.1.0
  source_maps: ^0.10.0
  source_span: ^1.0.2

dependency_overrides:
  angular2:
    path: ../angular2_clone

dev_dependencies:
  # We pin a specific version to ensure everyone is formatting the code exactly
  # the same way. This is because any change in dart_style, even non-breaking
  # changes, may change the output format.
  dart_style: 0.2.4
  test: ^0.12.0
  unittest: ^0.11.6
  webdriver: ^0.8.8

environment:
  sdk: ">=1.12.0 <2.0.0"

executables:
  # Similar to "analyzer.dart" and its command line "dartanalyzer" we use
  # "dartdevc".
  dartdevc: dartdevc
  dev_compiler: dartdevc

transformers:
- dev_compiler:
    compiler_args:
      - --no-summarize
    $include: ['example/hello_world.dart']
